# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: Song Yi Lee
google_analytics: Song Yi Lee
title: Song Yi Lee

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Song Yi Lee

description: Stylish Jekyll Theme
author:
  name: Song Yi Lee
  email: happypine37@gmail.com
  github: null
  twitter: null
  pinterest: null
  linkedin: null
  bio: Telephone : +82-010-4494-2646 E-mail : happypine37@gmail.com
  email_md5: 726351295ec82e145928582f595aa3aa



# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
